%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% This script uses the nomenclature, formulations and solutions from:
%   M. Avillez and D. Arnas, "Osculating and Mean Asynchronous Relative Motion Approximations 
%   Under J2 and Atmospheric Drag", TODO
%
% Summary:
%   Converts a mean relative state to an osculating relative state.
%   Implements the solution from section V.B of the paper.
%
% Inputs:
%   tt: argument of latitude at which to compute the mean relative state
%   mu: gravitational parameter
%   j2: J2 coefficient of the gravity model
%   R: Radius of the central planet
%   meanRelativeState: Mean relative state -> see Note 1
%   meanStateC: Mean state of the chief -> see Note 1
%   kD: Ballistic parameter of the deputy (D)
%   rhoD: Atmospheric density acting on the deputy (D)
%   kC: Ballistic parameter of the chief (C)
%   rhoC: Atmospheric density acting on the chief (C)
%   expansionOrder: Order of the expansion to use (2 or 3)
%
% Outputs:
%   osculatingRelativeState: Osculating relative state -> see Note 1
%
% Note 1:
%   Mean relative states: [dbbM; dxM; dyM; dpM; dooM; dtM]
%   Mean absolute states: [bbM; xM; yM; pM; ooM; tM]
%   Osculating relative states: [dbb; dx; dy; dp; doo; dt]
%
% Authors: Miguel Avillez and David Arnas
% Created: August 2025
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function osculatingRelativeState = meanToOscRelativeState(tt, mu, j2, R, meanRelativeState, meanStateC, ...
  kD, rhoD, kC, rhoC, expansionOrder)

  if expansionOrder == 2
    osculatingRelativeState = meanToOscRelativeStateOrder2(tt, mu, j2, R, meanRelativeState, meanStateC, kD, rhoD, kC, rhoC);
  elseif expansionOrder == 3
    osculatingRelativeState = meanToOscRelativeStateOrder3(tt, mu, j2, R, meanRelativeState, meanStateC, kD, rhoD, kC, rhoC);
  else
    error("Invalid expansion order")
  end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function: meanToOscRelativeStateOrder2
%
% Summary:
%   Converts a mean relative state to an osculating relative state, based on a 2nd order expansion.
%
% Inputs:
%   tt: argument of latitude at which to compute the mean relative state
%   mu: gravitational parameter
%   j2: J2 coefficient of the gravity model
%   R: Radius of the central planet
%   meanRelativeState: Mean relative state -> see Note 1
%   meanStateC: Mean state of the chief -> see Note 1
%   kD: Ballistic parameter of the deputy (D)
%   rhoD: Atmospheric density acting on the deputy (D)
%   kC: Ballistic parameter of the chief (C)
%   rhoC: Atmospheric density acting on the chief (C)
%
% Outputs:
%   osculatingRelativeState: Osculating relative state -> see Note 1
%
% Note 1:
%   Mean relative states: [dbbM; dxM; dyM; dpM; dooM; dtM]
%   Mean absolute states: [bbM; xM; yM; pM; ooM; tM]
%   Osculating relative states: [dbb; dx; dy; dp; doo; dt]
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function osculatingRelativeState = meanToOscRelativeStateOrder2(tt, mu, j2, R, meanRelativeState, ...
  meanStateC, kD, rhoD, kC, rhoC)

  % Extract individual elements of the chief's mean state
  bbM = meanStateC(1);
  xM = meanStateC(2);
  yM = meanStateC(3);
  pM = meanStateC(4);

  % Extract individual elements of the mean relative state
  dbbM = meanRelativeState(1);
  dxM = meanRelativeState(2);
  dyM = meanRelativeState(3);
  dpM = meanRelativeState(4);
  dooM = meanRelativeState(5);
  dtM = meanRelativeState(6);

  % Compute osculating relative elements
  dbb = dbbM+(3/4).*bbM.^4.*j2.*(2.*bbM.^3.*dpM.*pM+dbbM.*((-5)+7.* ...
    bbM.^2.*pM.^2)).*cos(2.*tt);
  dx = dxM+(1/4).*bbM.^3.*(3.*(5.*bbM.^3.*dpM.*pM+dbbM.*((-2)+15.* ...
    bbM.^2.*pM.^2)).*cos(tt)+(-7).*(bbM.^3.*dpM.*pM+dbbM.*((-2)+3.* ...
    bbM.^2.*pM.^2)).*cos(3.*tt))+bbM.^(-2).*j2.^(-1).*R.*(kC.*rhoC+( ...
    -1).*kD.*rhoD).*sin(tt);
  dy = dyM+bbM.^(-2).*j2.^(-1).*R.*((-1).*kC.*rhoC+kD.*rhoD).*cos(tt)+ ...
    bbM.^3.*sin(tt).*(6.*dbbM+7.*((-2).*dbbM+bbM.^3.*dpM.*pM+3.* ...
    bbM.^2.*dbbM.*pM.^2).*sin(tt).^2);
  dp = dpM;
  doo = dooM+(3/4).*bbM.^4.*j2.*(bbM.*dpM+5.*dbbM.*pM).*sin(2.*tt);
  dt = (1/4).*bbM.^(-5).*mu.^(-1/2).*(4.*bbM.^5.*dtM.*mu.^(1/2)+pi.^2.* ...
    R.^(5/2).*((-1).*kC.*rhoC+kD.*rhoD)+bbM.*j2.*R.^(3/2).*(8.*(bbM.* ...
    dyM+(-3).*dbbM.*yM).*cos(tt)+((-8).*bbM.*dxM+24.*dbbM.*xM+bbM.^4.* ...
    (14.*bbM.^3.*dpM.*pM+dbbM.*((-1)+21.*bbM.^2.*pM.^2)).*cos(tt)).* ...
    sin(tt)));

  % Concatenate the elements of the osculating relative state
  osculatingRelativeState = [dbb; dx; dy; dp; doo; dt];

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function: meanToOscRelativeStateOrder3
%
% Summary:
%   Converts a mean relative state to an osculating relative state, based on a 3rd order expansion.
%
% Inputs:
%   tt: argument of latitude at which to compute the mean relative state
%   mu: gravitational parameter
%   j2: J2 coefficient of the gravity model
%   R: Radius of the central planet
%   meanRelativeState: Mean relative state -> see Note 1
%   meanStateC: Mean state of the chief -> see Note 1
%   kD: Ballistic parameter of the deputy (D)
%   rhoD: Atmospheric density acting on the deputy (D)
%   kC: Ballistic parameter of the chief (C)
%   rhoC: Atmospheric density acting on the chief (C)
%
% Outputs:
%   osculatingRelativeState: Osculating relative state -> see Note 1
%
% Note 1:
%   Mean relative states: [dbbM; dxM; dyM; dpM; dooM; dtM]
%   Mean absolute states: [bbM; xM; yM; pM; ooM; tM]
%   Osculating relative states: [dbb; dx; dy; dp; doo; dt]
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function osculatingRelativeState = meanToOscRelativeStateOrder3(tt, mu, j2, R, meanRelativeState, ...
  meanStateC, kD, rhoD, kC, rhoC)

  % Extract individual elements of the chief's mean state
  bbM = meanStateC(1);
  xM = meanStateC(2);
  yM = meanStateC(3);
  pM = meanStateC(4);

  % Extract individual elements of the mean relative state
  dbbM = meanRelativeState(1);
  dxM = meanRelativeState(2);
  dyM = meanRelativeState(3);
  dpM = meanRelativeState(4);
  dooM = meanRelativeState(5);
  dtM = meanRelativeState(6);

  % Compute osculating relative elements
  dbb = dbbM+(1/32).*bbM.^(-1).*j2.*(8.*(3.*bbM.^5.*j2.*((-1).*bbM.*dxM+( ...
    -5).*dbbM.*xM+7.*bbM.^2.*dbbM.*pM.^2.*xM+bbM.^3.*pM.*(dxM.*pM+2.* ...
    dpM.*xM))+2.*R.*((-1).*kC.*rhoC+kD.*rhoD).*yM).*cos(tt)+6.* ...
    bbM.^4.*((-20).*bbM.*dbbM+(-40).*dbbM.^2+4.*bbM.^4.*dpM.^2+27.* ...
    bbM.^5.*dbbM.*j2+4.*bbM.^3.*dpM.*(2.*bbM+14.*dbbM+(-3).*bbM.^5.* ...
    j2).*pM+2.*bbM.^2.*dbbM.*(14.*bbM+42.*dbbM+(-33).*bbM.^5.*j2).* ...
    pM.^2+12.*bbM.^10.*dpM.*j2.*pM.^3+39.*bbM.^9.*dbbM.*j2.*pM.^4).* ...
    cos(2.*tt)+8.*bbM.^5.*j2.*((-1).*bbM.*dxM+(-5).*dbbM.*xM+7.* ...
    bbM.^2.*dbbM.*pM.^2.*xM+bbM.^3.*pM.*(dxM.*pM+2.*dpM.*xM)).*cos(3.* ...
    tt)+3.*bbM.^9.*j2.*(4.*bbM.^3.*dpM.*pM.*((-8)+11.*bbM.^2.*pM.^2)+ ...
    dbbM.*(45+(-176).*bbM.^2.*pM.^2+143.*bbM.^4.*pM.^4)).*cos(4.*tt)+( ...
    -8).*(2.*R.*((-1).*kC.*rhoC+kD.*rhoD).*xM+3.*bbM.^5.*j2.*((-1).* ...
    bbM.*dyM+(-5).*dbbM.*yM+7.*bbM.^2.*dbbM.*pM.^2.*yM+bbM.^3.*pM.*( ...
    dyM.*pM+2.*dpM.*yM))).*sin(tt)+(-4).*bbM.^4.*((-14)+11.*bbM.^2.* ...
    pM.^2).*R.*((-1).*kC.*rhoC+kD.*rhoD).*sin(2.*tt)+8.*bbM.^5.*j2.*(( ...
    -1).*bbM.*dyM+(-5).*dbbM.*yM+7.*bbM.^2.*dbbM.*pM.^2.*yM+bbM.^3.* ...
    pM.*(dyM.*pM+2.*dpM.*yM)).*sin(3.*tt));
  dx = dxM+(3/8).*bbM.^2.*((-4).*bbM.*dbbM+(-6).*dbbM.^2+5.*bbM.^4.* ...
    dpM.^2+(-12).*bbM.^5.*dbbM.*j2+2.*bbM.^3.*dpM.*(5.*bbM+30.*dbbM+ ...
    3.*bbM.^5.*j2).*pM+15.*bbM.^2.*dbbM.*(2.*bbM+5.*dbbM+2.*bbM.^5.* ...
    j2).*pM.^2+42.*bbM.^10.*dpM.*j2.*pM.^3+126.*bbM.^9.*dbbM.*j2.* ...
    pM.^4).*cos(tt)+(-1/48).*bbM.^(-3).*(12.*bbM.*(3.*bbM.^5.*j2.*(( ...
    -2).*bbM.*dxM+(-8).*dbbM.*xM+6.*bbM.^2.*dbbM.*pM.^2.*xM+bbM.^3.* ...
    pM.*(dxM.*pM+2.*dpM.*xM))+R.*((-1).*kC.*rhoC+kD.*rhoD).*yM).*cos( ...
    2.*tt)+3.*bbM.^5.*(2.*((-28).*bbM.*dbbM+(-42).*dbbM.^2+7.*bbM.^4.* ...
    dpM.^2+86.*bbM.^5.*dbbM.*j2)+bbM.^3.*dpM.*(28.*(bbM+6.*dbbM)+( ...
    -129).*bbM.^5.*j2).*pM+3.*bbM.^2.*dbbM.*(28.*bbM+70.*dbbM+(-215).* ...
    bbM.^5.*j2).*pM.^2+172.*bbM.^10.*dpM.*j2.*pM.^3+516.*bbM.^9.* ...
    dbbM.*j2.*pM.^4).*cos(3.*tt)+27.*bbM.^6.*j2.*((-1).*bbM.*dxM+(-4) ...
    .*dbbM.*xM+6.*bbM.^2.*dbbM.*pM.^2.*xM+bbM.^3.*pM.*(dxM.*pM+2.* ...
    dpM.*xM)).*cos(4.*tt)+9.*bbM.^10.*j2.*(bbM.^3.*dpM.*pM.*((-9)+16.* ...
    bbM.^2.*pM.^2)+dbbM.*(4+(-45).*bbM.^2.*pM.^2+48.*bbM.^4.*pM.^4)).* ...
    cos(5.*tt)+12.*j2.^(-1).*R.*(bbM.*kC.*((-4)+bbM.^4.*j2+(-1).* ...
    bbM.^6.*j2.*pM.^2).*rhoC+kD.*(4.*bbM+(-8).*dbbM+(-1).*bbM.^5.*j2+ ...
    bbM.^7.*j2.*pM.^2).*rhoD).*sin(tt)+(-12).*bbM.*(R.*((-1).*kC.* ...
    rhoC+kD.*rhoD).*xM+6.*bbM.^5.*j2.*((-4).*dbbM.*yM+bbM.*(dyM.*((-1) ...
    +2.*bbM.^2.*pM.^2)+4.*bbM.*pM.*(bbM.*dpM+3.*dbbM.*pM).*yM))).*sin( ...
    2.*tt)+(-28).*bbM.^5.*((-1)+bbM.^2.*pM.^2).*R.*((-1).*kC.*rhoC+ ...
    kD.*rhoD).*sin(3.*tt)+27.*bbM.^6.*j2.*((-1).*bbM.*dyM+(-4).*dbbM.* ...
    yM+6.*bbM.^2.*dbbM.*pM.^2.*yM+bbM.^3.*pM.*(dyM.*pM+2.*dpM.*yM)).* ...
    sin(4.*tt));
  dy = (1/48).*bbM.^(-3).*j2.^(-1).*((-12).*R.*(bbM.*kC.*(4+bbM.^4.*j2+( ...
    -1).*bbM.^6.*j2.*pM.^2).*rhoC+kD.*((-4).*bbM+8.*dbbM+(-1).* ...
    bbM.^5.*j2+bbM.^7.*j2.*pM.^2).*rhoD).*cos(tt)+bbM.*j2.*(48.* ...
    bbM.^2.*dyM+(-12).*(R.*((-1).*kC.*rhoC+kD.*rhoD).*xM+3.*bbM.^5.* ...
    j2.*((-12).*dbbM.*yM+bbM.*(dyM.*((-3)+4.*bbM.^2.*pM.^2)+8.*bbM.* ...
    pM.*(bbM.*dpM+3.*dbbM.*pM).*yM))).*cos(2.*tt)+(-28).*bbM.^4.*((-1) ...
    +bbM.^2.*pM.^2).*R.*((-1).*kC.*rhoC+kD.*rhoD).*cos(3.*tt)+3.*(9.* ...
    bbM.^5.*j2.*((-1).*bbM.*dyM+(-4).*dbbM.*yM+6.*bbM.^2.*dbbM.* ...
    pM.^2.*yM+bbM.^3.*pM.*(dyM.*pM+2.*dpM.*yM)).*cos(4.*tt)+6.* ...
    bbM.^4.*((-12).*bbM.*dbbM+(-18).*dbbM.^2+7.*bbM.^4.*dpM.^2+20.* ...
    bbM.^5.*dbbM.*j2+2.*bbM.^3.*dpM.*(7.*bbM+42.*dbbM+(-16).*bbM.^5.* ...
    j2).*pM+bbM.^2.*dbbM.*(42.*bbM+105.*dbbM+(-160).*bbM.^5.*j2).* ...
    pM.^2+102.*bbM.^10.*dpM.*j2.*pM.^3+306.*bbM.^9.*dbbM.*j2.*pM.^4).* ...
    sin(tt)+(-4).*(3.*bbM.^5.*j2.*((-1).*bbM.*dxM+(-4).*dbbM.*xM+6.* ...
    bbM.^2.*dbbM.*pM.^2.*xM+bbM.^3.*pM.*(dxM.*pM+2.*dpM.*xM))+R.*((-1) ...
    .*kC.*rhoC+kD.*rhoD).*yM).*sin(2.*tt)+(-1).*bbM.^4.*(2.*((-28).* ...
    bbM.*dbbM+(-42).*dbbM.^2+7.*bbM.^4.*dpM.^2+74.*bbM.^5.*dbbM.*j2)+ ...
    bbM.^3.*dpM.*(28.*(bbM+6.*dbbM)+(-99).*bbM.^5.*j2).*pM+3.*bbM.^2.* ...
    dbbM.*(28.*bbM+70.*dbbM+(-165).*bbM.^5.*j2).*pM.^2+124.*bbM.^10.* ...
    dpM.*j2.*pM.^3+372.*bbM.^9.*dbbM.*j2.*pM.^4).*sin(3.*tt)+(-9).* ...
    bbM.^5.*j2.*((-1).*bbM.*dxM+(-4).*dbbM.*xM+6.*bbM.^2.*dbbM.* ...
    pM.^2.*xM+bbM.^3.*pM.*(dxM.*pM+2.*dpM.*xM)).*sin(4.*tt)+(-3).* ...
    bbM.^9.*j2.*(bbM.^3.*dpM.*pM.*((-9)+16.*bbM.^2.*pM.^2)+dbbM.*(4+( ...
    -45).*bbM.^2.*pM.^2+48.*bbM.^4.*pM.^4)).*sin(5.*tt))));
  dp = dpM+(-1/8).*bbM.^(-2).*j2.*pM.*R.*((-1).*kC.*rhoC+kD.*rhoD).*((-4) ...
    .*xM.*sin(tt)+cos(tt).*(4.*yM+(bbM.^4+5.*bbM.^6.*pM.^2).*sin(tt)));
  doo = dooM+(1/2).*bbM.^3.*j2.*pi.^2.*pM.*R.*((-1).*kC.*rhoC+kD.*rhoD)+( ...
    1/32).*bbM.^3.*j2.*(72.*bbM.*j2.*(bbM.*dyM.*pM+bbM.*dpM.*yM+5.* ...
    dbbM.*pM.*yM).*cos(tt)+48.*pM.*R.*((-1).*kC.*rhoC+kD.*rhoD).*cos( ...
    2.*tt)+(-8).*bbM.*j2.*(bbM.*dyM.*pM+bbM.*dpM.*yM+5.*dbbM.*pM.*yM) ...
    .*cos(3.*tt)+(-24).*bbM.*j2.*(bbM.*dxM.*pM+bbM.*dpM.*xM+5.*dbbM.* ...
    pM.*xM).*sin(tt)+6.*(bbM.*dpM.*(4.*bbM+20.*dbbM+7.*bbM.^5.*j2)+ ...
    dbbM.*(20.*bbM+40.*dbbM+63.*bbM.^5.*j2).*pM+(-39).*bbM.^8.*dpM.* ...
    j2.*pM.^2+(-143).*bbM.^7.*dbbM.*j2.*pM.^3).*sin(2.*tt)+8.*bbM.* ...
    j2.*(bbM.*dxM.*pM+bbM.*dpM.*xM+5.*dbbM.*pM.*xM).*sin(3.*tt)+3.* ...
    bbM.^5.*j2.*((-5).*bbM.*dpM+(-45).*dbbM.*pM+24.*bbM.^3.*dpM.* ...
    pM.^2+88.*bbM.^2.*dbbM.*pM.^3).*sin(4.*tt));
  dt = (1/192).*bbM.^(-6).*j2.*mu.^(-1/2).*(12.*j2.^(-1).*(16.*bbM.^6.* ...
    dtM.*mu.^(1/2)+(-20).*dbbM.*kD.*pi.^2.*R.^(5/2).*rhoD+4.*bbM.* ...
    pi.^2.*R.^(5/2).*((-1).*kC.*rhoC+kD.*rhoD)+bbM.^5.*j2.*(48+pi.^2) ...
    .*R.^(5/2).*((-1).*kC.*rhoC+kD.*rhoD)+(-1).*bbM.^7.*j2.*(144+7.* ...
    pi.^2).*pM.^2.*R.^(5/2).*((-1).*kC.*rhoC+kD.*rhoD))+96.*bbM.*R.^( ...
    3/2).*(4.*bbM.^2.*dyM+9.*bbM.^6.*dyM.*j2+2.*kC.*R.*rhoC.*xM+(-2).* ...
    kD.*R.*rhoD.*xM+24.*dbbM.^2.*yM+9.*bbM.^5.*dbbM.*j2.*yM+(-81).* ...
    bbM.^7.*dbbM.*j2.*pM.^2.*yM+(-12).*bbM.*dbbM.*(dyM+yM)+(-27).* ...
    bbM.^8.*j2.*pM.*(dyM.*pM+2.*dpM.*yM)).*cos(tt)+(-1).*bbM.*R.^(3/2) ...
    .*(2.*bbM.*(107.*bbM.^5.*pM.^2.*R.*(kC.*rhoC+(-1).*kD.*rhoD)+17.* ...
    bbM.^3.*R.*((-1).*kC.*rhoC+kD.*rhoD)+(-432).*dbbM.*j2.*xM.*yM+ ...
    144.*bbM.*j2.*(dyM.*xM+dxM.*yM)).*cos(2.*tt)+3.*(8.*bbM.^5.*j2.*( ...
    dbbM.*yM+bbM.*(dyM+(-5).*bbM.^2.*dyM.*pM.^2+(-5).*bbM.*pM.*(2.* ...
    bbM.*dpM+3.*dbbM.*pM).*yM)).*cos(3.*tt)+64.*(2.*bbM.^2.*dxM+3.* ...
    bbM.^6.*dxM.*j2+12.*dbbM.^2.*xM+3.*bbM.^5.*dbbM.*j2.*xM+(-36).* ...
    bbM.^7.*dbbM.*j2.*pM.^2.*xM+(-6).*bbM.*dbbM.*(dxM+xM)+(-12).* ...
    bbM.^8.*j2.*pM.*(dxM.*pM+2.*dpM.*xM)+R.*((-1).*kC.*rhoC+kD.*rhoD) ...
    .*yM).*sin(tt)+2.*bbM.*(4.*bbM.^4.*dbbM+(-5).*bbM.^8.*dbbM.*j2+( ...
    -144).*bbM.^11.*dpM.*j2.*pM+(-84).*bbM.^5.*dbbM.^2.*pM.^2+(-504).* ...
    bbM.^10.*dbbM.*j2.*pM.^2+724.*bbM.^13.*dpM.*j2.*pM.^3+1629.* ...
    bbM.^12.*dbbM.*j2.*pM.^4+(-84).*bbM.^6.*dbbM.*pM.*(2.*dpM+pM)+( ...
    -28).*bbM.^7.*dpM.*(dpM+2.*pM)+72.*dbbM.*j2.*(xM+(-1).*yM).*(xM+ ...
    yM)+48.*bbM.*j2.*((-1).*dxM.*xM+dyM.*yM)).*sin(2.*tt)+(-8).* ...
    bbM.^5.*j2.*(dbbM.*xM+bbM.*(dxM+(-5).*bbM.^2.*dxM.*pM.^2+(-5).* ...
    bbM.*pM.*(2.*bbM.*dpM+3.*dbbM.*pM).*xM)).*sin(3.*tt)+(-3).* ...
    bbM.^9.*j2.*((-34).*bbM.^3.*dpM.*pM+88.*bbM.^5.*dpM.*pM.^3+dbbM.*( ...
    5+(-119).*bbM.^2.*pM.^2+198.*bbM.^4.*pM.^4)).*sin(4.*tt))));

  % Concatenate the elements of the osculating relative state
  osculatingRelativeState = [dbb; dx; dy; dp; doo; dt];

end