%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% This script uses the nomenclature, formulations and solutions from:
%   M. Avillez and D. Arnas, "Osculating and Mean Asynchronous Relative Motion Approximations 
%   Under J2 and Atmospheric Drag", TODO
%
% Summary:
%   Converts an osculating relative state to a mean relative state.
%   Implements the solution from section V.A of the paper.
%
% Inputs:
%   tt: argument of latitude at which to compute the mean relative state
%   mu: gravitational parameter
%   j2: J2 coefficient of the gravity model
%   R: Radius of the central planet
%   osculatingRelativeState: Osculating relative state -> see Note 1
%   osculatingStateC: Osculating state of the chief -> see Note 1
%   kD: Ballistic parameter of the deputy (D)
%   rhoD: Atmospheric density acting on the deputy (D)
%   kC: Ballistic parameter of the chief (C)
%   rhoC: Atmospheric density acting on the chief (C)
%   expansionOrder: Order of the expansion to use (2 or 3)
%
% Outputs:
%   meanRelativeState: Mean relative state -> see Note 1
%
% Note 1:
%   Mean relative states: [dbbM; dxM; dyM; dpM; dooM; dtM]
%   Osculating absolute states: [bb; x; y; p; oo; t]
%   Osculating relative states: [dbb; dx; dy; dp; doo; dt]
%
% Authors: Miguel Avillez and David Arnas
% Created: August 2025
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function meanRelativeState = oscToMeanRelativeState(tt, mu, j2, R, osculatingRelativeState, osculatingStateC, ...
  kD, rhoD, kC, rhoC, expansionOrder)

  if expansionOrder == 2
    meanRelativeState = oscToMeanRelativeStateOrder2(tt, mu, j2, R, osculatingRelativeState, osculatingStateC, kD, rhoD, kC, rhoC);
  elseif expansionOrder == 3
    meanRelativeState = oscToMeanRelativeStateOrder3(tt, mu, j2, R, osculatingRelativeState, osculatingStateC, kD, rhoD, kC, rhoC);
  else
    error("Invalid expansion order")
  end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function: meanToOscRelativeStateOrder2
%
% Summary:
%   Converts an osculating relative state to a mean relative state, based on a 2nd order expansion.
%
% Inputs:
%   tt: argument of latitude at which to compute the mean relative state
%   mu: gravitational parameter
%   j2: J2 coefficient of the gravity model
%   R: Radius of the central planet
%   osculatingRelativeState: Osculating relative state -> see Note 1
%   osculatingStateC: Osculating state of the chief -> see Note 1
%   kD: Ballistic parameter of the deputy (D)
%   rhoD: Atmospheric density acting on the deputy (D)
%   kC: Ballistic parameter of the chief (C)
%   rhoC: Atmospheric density acting on the chief (C)
%
% Outputs:
%   meanRelativeState: Mean relative state -> see Note 1
%
% Note 1:
%   Mean relative states: [dbbM; dxM; dyM; dpM; dooM; dtM]
%   Osculating absolute states: [bb; x; y; p; oo; t]
%   Osculating relative states: [dbb; dx; dy; dp; doo; dt]
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function meanRelativeState = oscToMeanRelativeStateOrder2(tt, mu, j2, R, osculatingRelativeState, ...
  osculatingStateC, kD, rhoD, kC, rhoC)

  % Extract individual elements of the chief's osculating state
  bb = osculatingStateC(1);
  x = osculatingStateC(2);
  y = osculatingStateC(3);
  p = osculatingStateC(4);

  % Extract individual elements of the osculating relative state
  dbb = osculatingRelativeState(1);
  dx = osculatingRelativeState(2);
  dy = osculatingRelativeState(3);
  dp = osculatingRelativeState(4);
  doo = osculatingRelativeState(5);
  dt = osculatingRelativeState(6);

  % Compute mean relative elements
  dbbM = dbb+(-3/4).*bb.^4.*j2.*(2.*bb.^3.*dp.*p+dbb.*((-5)+7.*bb.^2.*p.^2) ...
    ).*cos(2.*tt);
  dxM = dx+(1/4).*bb.^3.*((-3).*(5.*bb.^3.*dp.*p+dbb.*((-2)+15.*bb.^2.* ...
    p.^2)).*cos(tt)+7.*(bb.^3.*dp.*p+dbb.*((-2)+3.*bb.^2.*p.^2)).*cos( ...
    3.*tt))+bb.^(-2).*j2.^(-1).*R.*((-1).*kC.*rhoC+kD.*rhoD).*sin(tt);
  dyM = dy+bb.^(-2).*j2.^(-1).*R.*(kC.*rhoC+(-1).*kD.*rhoD).*cos(tt)+ ...
    bb.^3.*sin(tt).*((-6).*dbb+(-7).*((-2).*dbb+bb.^3.*dp.*p+3.* ...
    bb.^2.*dbb.*p.^2).*sin(tt).^2);
  dpM = dp;
  dooM = doo+(-3/4).*bb.^4.*j2.*(bb.*dp+5.*dbb.*p).*sin(2.*tt);
  dtM = (1/4).*bb.^(-5).*mu.^(-1/2).*(4.*bb.^5.*dt.*mu.^(1/2)+(-1).*((-8)+ ...
    pi.^2).*R.^(5/2).*((-1).*kC.*rhoC+kD.*rhoD)+bb.*j2.*R.^(3/2).*(8.* ...
    (bb.*dx+(-3).*dbb.*x).*sin(tt)+cos(tt).*((-8).*bb.*dy+24.*dbb.*y+( ...
    9.*bb.^4.*dbb+(-30).*bb.^7.*dp.*p+(-45).*bb.^6.*dbb.*p.^2).*sin( ...
    tt))));

  % Concatenate the elements of the mean relative state
  meanRelativeState = [dbbM; dxM; dyM; dpM; dooM; dtM];

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function: meanToOscRelativeStateOrder3
%
% Summary:
%   Converts an osculating relative state to a mean relative state, based on a 2nd order expansion.
%
% Inputs:
%   tt: argument of latitude at which to compute the mean relative state
%   mu: gravitational parameter
%   j2: J2 coefficient of the gravity model
%   R: Radius of the central planet
%   osculatingRelativeState: Osculating relative state -> see Note 1
%   osculatingStateC: Osculating state of the chief -> see Note 1
%   kD: Ballistic parameter of the deputy (D)
%   rhoD: Atmospheric density acting on the deputy (D)
%   kC: Ballistic parameter of the chief (C)
%   rhoC: Atmospheric density acting on the chief (C)
%
% Outputs:
%   meanRelativeState: Mean relative state -> see Note 1
%
% Note 1:
%   Mean relative states: [dbbM; dxM; dyM; dpM; dooM; dtM]
%   Osculating absolute states: [bb; x; y; p; oo; t]
%   Osculating relative states: [dbb; dx; dy; dp; doo; dt]
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function meanRelativeState = oscToMeanRelativeStateOrder3(tt, mu, j2, R, osculatingRelativeState, ...
  osculatingStateC, kD, rhoD, kC, rhoC)

  % Extract individual elements of the chief's osculating state
  bb = osculatingStateC(1);
  x = osculatingStateC(2);
  y = osculatingStateC(3);
  p = osculatingStateC(4);

  % Extract individual elements of the osculating relative state
  dbb = osculatingRelativeState(1);
  dx = osculatingRelativeState(2);
  dy = osculatingRelativeState(3);
  dp = osculatingRelativeState(4);
  doo = osculatingRelativeState(5);
  dt = osculatingRelativeState(6);

  % Compute mean relative elements
  dbbM = (1/32).*bb.^(-1).*j2.*(32.*bb.*dbb.*j2.^(-1)+261.*bb.^9.*dbb.*j2+( ...
    -152).*bb.^12.*dp.*j2.*p+(-836).*bb.^11.*dbb.*j2.*p.^2+188.* ...
    bb.^14.*dp.*j2.*p.^3+611.*bb.^13.*dbb.*j2.*p.^4+8.*(3.*bb.^5.*j2.* ...
    (bb.*dx+5.*dbb.*x+(-7).*bb.^2.*dbb.*p.^2.*x+(-1).*bb.^3.*p.*(dx.* ...
    p+2.*dp.*x))+2.*R.*(kC.*rhoC+(-1).*kD.*rhoD).*y).*cos(tt)+6.* ...
    bb.^4.*(20.*bb.*dbb+40.*dbb.^2+(-4).*bb.^4.*dp.^2+9.*bb.^5.*dbb.* ...
    j2+(-4).*bb.^3.*dp.*(2.*bb+14.*dbb+5.*bb.^5.*j2).*p+(-2).*bb.^2.* ...
    dbb.*(14.*bb+42.*dbb+55.*bb.^5.*j2).*p.^2+36.*bb.^10.*dp.*j2.* ...
    p.^3+117.*bb.^9.*dbb.*j2.*p.^4).*cos(2.*tt)+8.*bb.^5.*j2.*(bb.*dx+ ...
    5.*dbb.*x+(-7).*bb.^2.*dbb.*p.^2.*x+(-1).*bb.^3.*p.*(dx.*p+2.*dp.* ...
    x)).*cos(3.*tt)+6.*bb.^9.*j2.*((-1)+bb.^2.*p.^2).*(4.*bb.^3.*dp.* ...
    p+dbb.*((-9)+13.*bb.^2.*p.^2)).*cos(4.*tt)+8.*(2.*R.*((-1).*kC.* ...
    rhoC+kD.*rhoD).*x+3.*bb.^5.*j2.*((-1).*bb.*dy+(-5).*dbb.*y+7.* ...
    bb.^2.*dbb.*p.^2.*y+bb.^3.*p.*(dy.*p+2.*dp.*y))).*sin(tt)+4.* ...
    bb.^4.*((-8)+5.*bb.^2.*p.^2).*R.*((-1).*kC.*rhoC+kD.*rhoD).*sin( ...
    2.*tt)+8.*bb.^5.*j2.*(bb.*dy+5.*dbb.*y+(-7).*bb.^2.*dbb.*p.^2.*y+( ...
    -1).*bb.^3.*p.*(dy.*p+2.*dp.*y)).*sin(3.*tt));
  dxM = (1/96).*bb.^(-3).*j2.^(-1).*(96.*bb.^3.*dx.*j2+9.*bb.^5.*j2.*(16.* ...
    bb.*dbb+24.*dbb.^2+(-20).*bb.^4.*dp.^2+74.*bb.^5.*dbb.*j2+(-1).* ...
    bb.^3.*dp.*(40.*(bb+6.*dbb)+101.*bb.^5.*j2).*p+(-5).*bb.^2.*dbb.*( ...
    24.*bb+60.*dbb+101.*bb.^5.*j2).*p.^2+45.*bb.^10.*dp.*j2.*p.^3+ ...
    135.*bb.^9.*dbb.*j2.*p.^4).*cos(tt)+24.*bb.*j2.*(3.*bb.^5.*j2.*(( ...
    -2).*bb.*dx+(-8).*dbb.*x+6.*bb.^2.*dbb.*p.^2.*x+bb.^3.*p.*(dx.*p+ ...
    2.*dp.*x))+R.*((-1).*kC.*rhoC+kD.*rhoD).*y).*cos(2.*tt)+3.*bb.^5.* ...
    j2.*(28.*((-4).*bb.*dbb+(-6).*dbb.^2+bb.^4.*dp.^2)+92.*bb.^5.* ...
    dbb.*j2+bb.^3.*dp.*(56.*(bb+6.*dbb)+(-123).*bb.^5.*j2).*p+3.* ...
    bb.^2.*dbb.*(56.*bb+140.*dbb+(-205).*bb.^5.*j2).*p.^2+128.* ...
    bb.^10.*dp.*j2.*p.^3+384.*bb.^9.*dbb.*j2.*p.^4).*cos(3.*tt)+54.* ...
    bb.^6.*j2.^2.*((-1).*bb.*dx+(-4).*dbb.*x+6.*bb.^2.*dbb.*p.^2.*x+ ...
    bb.^3.*p.*(dx.*p+2.*dp.*x)).*cos(4.*tt)+9.*bb.^10.*j2.^2.*(bb.^3.* ...
    dp.*p.*((-20)+27.*bb.^2.*p.^2)+dbb.*(26+(-100).*bb.^2.*p.^2+81.* ...
    bb.^4.*p.^4)).*cos(5.*tt)+3.*R.*((-64).*dbb.*kD.*rhoD+32.*bb.*(( ...
    -1).*kC.*rhoC+kD.*rhoD)+3.*bb.^5.*j2.*((-1).*kC.*rhoC+kD.*rhoD)+ ...
    45.*bb.^7.*j2.*p.^2.*((-1).*kC.*rhoC+kD.*rhoD)).*sin(tt)+(-24).* ...
    bb.*j2.*(R.*((-1).*kC.*rhoC+kD.*rhoD).*x+6.*bb.^5.*j2.*((-4).* ...
    dbb.*y+bb.*(dy.*((-1)+2.*bb.^2.*p.^2)+4.*bb.*p.*(bb.*dp+3.*dbb.*p) ...
    .*y))).*sin(2.*tt)+bb.^5.*j2.*((-97)+133.*bb.^2.*p.^2).*R.*((-1).* ...
    kC.*rhoC+kD.*rhoD).*sin(3.*tt)+54.*bb.^6.*j2.^2.*((-1).*bb.*dy+( ...
    -4).*dbb.*y+6.*bb.^2.*dbb.*p.^2.*y+bb.^3.*p.*(dy.*p+2.*dp.*y)).* ...
    sin(4.*tt));
  dyM = (1/96).*bb.^(-3).*j2.^(-1).*((-3).*R.*((-64).*dbb.*kD.*rhoD+39.* ...
    bb.^5.*j2.*(kC.*rhoC+(-1).*kD.*rhoD)+32.*bb.*((-1).*kC.*rhoC+kD.* ...
    rhoD)+63.*bb.^7.*j2.*p.^2.*((-1).*kC.*rhoC+kD.*rhoD)).*cos(tt)+ ...
    bb.*j2.*(96.*bb.^2.*dy+24.*(R.*((-1).*kC.*rhoC+kD.*rhoD).*x+3.* ...
    bb.^5.*j2.*((-12).*dbb.*y+bb.*(dy.*((-3)+4.*bb.^2.*p.^2)+8.*bb.* ...
    p.*(bb.*dp+3.*dbb.*p).*y))).*cos(2.*tt)+(-1).*bb.^4.*((-97)+133.* ...
    bb.^2.*p.^2).*R.*((-1).*kC.*rhoC+kD.*rhoD).*cos(3.*tt)+(-54).* ...
    bb.^5.*j2.*((-1).*bb.*dy+(-4).*dbb.*y+6.*bb.^2.*dbb.*p.^2.*y+ ...
    bb.^3.*p.*(dy.*p+2.*dp.*y)).*cos(4.*tt)+(-9).*bb.^4.*((-48).*bb.* ...
    dbb+(-72).*dbb.^2+28.*bb.^4.*dp.^2+142.*bb.^5.*dbb.*j2+bb.^3.*dp.* ...
    (56.*(bb+6.*dbb)+(-223).*bb.^5.*j2).*p+bb.^2.*dbb.*(168.*bb+420.* ...
    dbb+(-1115).*bb.^5.*j2).*p.^2+543.*bb.^10.*dp.*j2.*p.^3+1629.* ...
    bb.^9.*dbb.*j2.*p.^4).*sin(tt)+24.*(3.*bb.^5.*j2.*((-1).*bb.*dx+( ...
    -4).*dbb.*x+6.*bb.^2.*dbb.*p.^2.*x+bb.^3.*p.*(dx.*p+2.*dp.*x))+R.* ...
    ((-1).*kC.*rhoC+kD.*rhoD).*y).*sin(2.*tt)+3.*bb.^4.*(4.*((-28).* ...
    bb.*dbb+(-42).*dbb.^2+7.*bb.^4.*dp.^2+65.*bb.^5.*dbb.*j2)+bb.^3.* ...
    dp.*(56.*(bb+6.*dbb)+(-225).*bb.^5.*j2).*p+3.*bb.^2.*dbb.*(56.*bb+ ...
    140.*dbb+(-375).*bb.^5.*j2).*p.^2+248.*bb.^10.*dp.*j2.*p.^3+744.* ...
    bb.^9.*dbb.*j2.*p.^4).*sin(3.*tt)+54.*bb.^5.*j2.*((-1).*bb.*dx+( ...
    -4).*dbb.*x+6.*bb.^2.*dbb.*p.^2.*x+bb.^3.*p.*(dx.*p+2.*dp.*x)).* ...
    sin(4.*tt)+9.*bb.^9.*j2.*(bb.^3.*dp.*p.*((-20)+27.*bb.^2.*p.^2)+ ...
    dbb.*(26+(-100).*bb.^2.*p.^2+81.*bb.^4.*p.^4)).*sin(5.*tt)));
  dpM = dp+(1/16).*bb.^(-2).*j2.*p.*R.*((-1).*kC.*rhoC+kD.*rhoD).*(8.*y.* ...
    cos(tt)+(-8).*x.*sin(tt)+3.*bb.^4.*((-1)+3.*bb.^2.*p.^2).*sin(2.*tt));
  dooM = doo+(-1/2).*bb.^3.*j2.*p.*((-3)+pi.^2).*R.*((-1).*kC.*rhoC+kD.* ...
    rhoD)+(1/32).*bb.^3.*j2.*((-72).*bb.*j2.*(bb.*dy.*p+bb.*dp.*y+5.* ...
    dbb.*p.*y).*cos(tt)+32.*p.*R.*(kC.*rhoC+(-1).*kD.*rhoD).*cos(2.* ...
    tt)+8.*bb.*j2.*(bb.*dy.*p+bb.*dp.*y+5.*dbb.*p.*y).*cos(3.*tt)+24.* ...
    bb.*j2.*(bb.*dx.*p+bb.*dp.*x+5.*dbb.*p.*x).*sin(tt)+(-6).*(bb.* ...
    dp.*(4.*bb+20.*dbb+7.*bb.^5.*j2)+dbb.*(20.*bb+40.*dbb+63.*bb.^5.* ...
    j2).*p+(-63).*bb.^8.*dp.*j2.*p.^2+(-231).*bb.^7.*dbb.*j2.*p.^3).* ...
    sin(2.*tt)+(-8).*bb.*j2.*(bb.*dx.*p+bb.*dp.*x+5.*dbb.*p.*x).*sin( ...
    3.*tt)+(-3).*bb.^5.*j2.*(2.*bb.*dp+18.*dbb.*p+3.*bb.^3.*dp.*p.^2+ ...
    11.*bb.^2.*dbb.*p.^3).*sin(4.*tt));
  dtM = (1/64).*bb.^(-6).*j2.*mu.^(-1/2).*(4.*j2.^(-1).*(16.*bb.^6.*dt.* ...
    mu.^(1/2)+20.*dbb.*kD.*((-8)+pi.^2).*R.^(5/2).*rhoD+(-4).*bb.*(( ...
    -8)+pi.^2).*R.^(5/2).*((-1).*kC.*rhoC+kD.*rhoD)+(-1).*bb.^5.*j2.*( ...
    12+pi.^2).*R.^(5/2).*((-1).*kC.*rhoC+kD.*rhoD)+bb.^7.*j2.*p.^2.*( ...
    12+7.*pi.^2).*R.^(5/2).*((-1).*kC.*rhoC+kD.*rhoD))+bb.*R.^(3/2).*( ...
    4.*((-32).*bb.^2.*dy+21.*bb.^6.*dy.*j2+16.*R.*(kC.*rhoC+(-1).*kD.* ...
    rhoD).*x+(-192).*dbb.^2.*y+21.*bb.^5.*dbb.*j2.*y+153.*bb.^7.*dbb.* ...
    j2.*p.^2.*y+96.*bb.*dbb.*(dy+y)+51.*bb.^8.*j2.*p.*(dy.*p+2.*dp.*y) ...
    ).*cos(tt)+2.*bb.*(5.*bb.^3.*((-41)+6.*pi.^2).*R.*((-1).*kC.*rhoC+ ...
    kD.*rhoD)+(-1).*bb.^5.*p.^2.*((-191)+30.*pi.^2).*R.*((-1).*kC.* ...
    rhoC+kD.*rhoD)+(-144).*dbb.*j2.*x.*y+48.*bb.*j2.*(dy.*x+dx.*y)).* ...
    cos(2.*tt)+(-4).*bb.^5.*j2.*((-23).*bb.*dy+(-23).*dbb.*y+57.* ...
    bb.^2.*dbb.*p.^2.*y+19.*bb.^3.*p.*(dy.*p+2.*dp.*y)).*cos(3.*tt)+( ...
    -4).*((-32).*bb.^2.*dx+(-81).*bb.^6.*dx.*j2+(-192).*dbb.^2.*x+( ...
    -81).*bb.^5.*dbb.*j2.*x+531.*bb.^7.*dbb.*j2.*p.^2.*x+96.*bb.*dbb.* ...
    (dx+x)+177.*bb.^8.*j2.*p.*(dx.*p+2.*dp.*x)+16.*R.*((-1).*kC.*rhoC+ ...
    kD.*rhoD).*y).*sin(tt)+6.*bb.*(12.*bb.^4.*dbb+95.*bb.^8.*dbb.*j2+( ...
    -320).*bb.^11.*dp.*j2.*p+(-60).*bb.^5.*dbb.^2.*p.^2+(-1120).* ...
    bb.^10.*dbb.*j2.*p.^2+772.*bb.^13.*dp.*j2.*p.^3+1737.*bb.^12.* ...
    dbb.*j2.*p.^4+(-60).*bb.^6.*dbb.*p.*(2.*dp+p)+(-20).*bb.^7.*dp.*( ...
    dp+2.*p)+24.*dbb.*j2.*(x+(-1).*y).*(x+y)+16.*bb.*j2.*((-1).*dx.*x+ ...
    dy.*y)).*sin(2.*tt)+4.*bb.^5.*j2.*((-23).*bb.*dx+(-23).*dbb.*x+ ...
    57.*bb.^2.*dbb.*p.^2.*x+19.*bb.^3.*p.*(dx.*p+2.*dp.*x)).*sin(3.* ...
    tt)+(-3).*bb.^9.*j2.*(2.*bb.^3.*dp.*p.*((-63)+86.*bb.^2.*p.^2)+ ...
    dbb.*(130+(-441).*bb.^2.*p.^2+387.*bb.^4.*p.^4)).*sin(4.*tt)));

  % Concatenate the elements of the mean relative state
  meanRelativeState = [dbbM; dxM; dyM; dpM; dooM; dtM];

end